const produtos = {
  mouses: [
    {
      id: "M001",
      name: "Mouse Gamer Cobra Chroma M711 Rgb Redragon",
      brand: "Redragon",
      dpi: 10.000,
      color: ["black", "white"],
      bluetooth: false,
      buttons: 8,
      stores: ["KaBuM!", "Terabyteshop", "Pichau"],
      prices: [114.90, 116.90, 129.90],
    },
    {
      id: "M002",
      name: "Mouse Gamer Logitech G203 Rgb Lightsync",
      brand: "Logitech",
      dpi: 8.000,
      color: ["black", "white"],
      bluetooth: false,
      buttons: 6,
      stores: ["KaBuM!", "Terabyteshop", "Kalunga"],
      prices: [119.90, 129.90, 161.90],
    },
    {
      id: "M003",
      name: "Mouse Gamer Logitech G203 Rgb Lightsync",
      brand: "Logitech",
      dpi: 1.000,
      color: ["black", "white"],
      bluetooth: false,
      buttons: 6,
      stores: ["Shopee", "KaBuM!", "Kalunga"],
      prices: [119.00, 124.90, 129.90],
    },
    {
      id: "M004",
      name: "Mouse Logitech M170",
      brand: "Logitech",
      dpi: 1.000,
      color: ["black", "white", "red"],
      bluetooth: true,
      buttons: 3,
      stores: ["Shopee", "Kabum!", "Kalunga"],
      prices: [10.10, 69.90, 69.90],
    },
    {
      id: "M005",
      name: "Mouse Gamer 3200dpi MO273-Multilaser",
      brand: "Multilaser",
      dpi: 3.200,
      color: ["green", "orange"],
      bluetooth: false,
      buttons: 6,
      stores: ["Loja Multilaser", "KaBuM!", "Kalunga"],
      prices: [59.90, 52.90, 69.80],
    },
    {
      id: "M006",
      name: "Mouse Gamer Rgb Gt-m3 Lehmox",
      brand: "Lehmox",
      dpi: 1.200,
      color: ["black", "red"],
      bluetooth: false,
      buttons: 4,
      stores: ["Mercado Livre", "Magazine Luiza", "Submarino"],
      prices: [17.90, 44.91, 45.78],
    },
    {
      id: "M007",
      name: "Mouse Gamer K-Mex",
      brand: "K-Mex",
      dpi: 1.600,
      color: ["black", "blue"],
      bluetooth: false,
      buttons: 3,
      stores: ["Submarino", "Magazine Luiza", "Casas Bahia"],
      prices: [17.14, 26.95, 27.43],
    },
    {
      id: "M008",
      name: "Mouse Logitech Mx Master 3",
      brand: "Logitech",
      dpi: 4.000,
      color: ["white"],
      bluetooth: true,
      buttons: 7,
      stores: ["Mercado Livre", "KaBuM!", "Pichau"],
      prices: [570.63, 599.90, 499.90],
    },
    {
      id: "M009",
      name: "Mouse Jogo Notebook Pc Gamer",
      brand: "Dpx",
      dpi: 2.400,
      color: ["black", "white", "blue"],
      bluetooth: true,
      buttons: 3,
      stores: ["Americanas", "Shoptime", "Submarino"],
      prices: [39.99, 39.99, 39.99],
    },
    {
      id: "M010",
      name: "Mouse Multilaser MO221",
      brand: "Multilaser",
      dpi: 1.600,
      color: ["white", "blue"],
      bluetooth: true,
      buttons: 3,
      stores: ["Submarino", "Shoptime", "Americanas"],
      prices: [35.34, 34.96, 38.64],
    },
  ],
  keyboards: [
    {
      id: "K001",
      name: "Teclado Logitech K120, ABNT2",
      brand: "Logitech",
      color: ["black"],
      bluetooth: true,
      stores: ["KaBuM!", "Submarino", "Americanas"],
      prices: [59.90, 63.49, 78.00],
    },
    {
      id: "K002",
      name: "Teclado Mecanico Pichau P531 RGB",
      brand: "Pichau Gaming",
      color: ["black"],
      bluetooth: false,
      stores: ["KaBuM!", "Submarino", "Pichau"],
      prices: [229.90, 245.60, 259.99],
    },
    {
      id: "K003",
      name: "Teclado Mecanico Pichau P531 RGB",
      brand: "Pichau Gaming",
      color: ["black"],
      bluetooth: false,
      stores: ["KaBuM!", "Submarino", "Pichau"],
      prices: [229.90, 245.60, 259.99],
    },
    {
      id: "K004",
      name: "Teclado Mecanico Gamer Corsair K60 PRO",
      brand: "Corsair",
      color: ["black", "red"],
      bluetooth: true,
      stores: ["KaBuM!", "Americanas", "Pichau"],
      prices: [289.90, 325.00, 310.99],
    },
    {
      id: "K005",
      name: "Teclado Mecanico Gamer Redragon Daska, Rainbow",
      brand: "Redragon",
      color: ["black", "white"],
      bluetooth: true,
      stores: ["KaBuM!", "Magazine Luiza", "Pichau"],
      prices: [219.00, 230.60, 250.99],
    },
    {
      id: "K006",
      name: "Teclado Opto-Mecanico Redragon Infernal Dragon Viserion",
      brand: "Redragon",
      color: ["black", "red"],
      bluetooth: false,
      stores: ["Submarino", "Americanas", "Pichau"],
      prices: [419.90, 425.59, 440.00],
    },
    {
      id: "K007",
      name: "Teclado Mecanico T-Dagger Bermudo",
      brand: "T-Dagger",
      color: ["black", "grey"],
      bluetooth: true,
      stores: ["Submarino", "Americanas", "Pichau"],
      prices: [205.00, 220.99, 225.99],
    },
    {
      id: "K008",
      name: "Teclado Mecanico Gamer Corsair K60 PRO",
      brand: "Corsair",
      color: ["black", "red"],
      bluetooth: true,
      stores: ["KaBuM!", "Americanas", "Pichau"],
      prices: [289.90, 325.00, 310.99],
    },
    {
      id: "K009",
      name: "Teclado Gamer Trust GXT 835 Azor",
      brand: "Trust",
      color: ["black"],
      bluetooth: false,
      stores: ["KaBuM!", "Americanas", "Pichau"],
      prices: [149.90, 160.66, 180.99],
    },
    {
      id: "K010",
      name: "Teclado Gamer Multilaser Multimidia USB PRETO/VERDE",
      brand: "Multilaser",
      color: ["black", "green"],
      bluetooth: false,
      stores: ["KaBuM!", "Submarino", "Pichau"],
      prices: [34.90, 40.00, 43.99],
    },
  ],
  headset: [
    {
      id: "H001",
      name: "",
      brand: "",
      color: [""],
      bluetooth: true,
      stores: ["", "", ""],
      prices: [, , ],
    },
  ],
};

module.exports = produtos;
