const produtos = {
  mouses: [
    {
      id: "M001",
      name: "Mouse Gamer Cobra Chroma M711 Rgb Redragon",
      brand: "Redragon",
      dpi: 10.000,
      color: ["black", "white"],
      bluetooth: false,
      buttons: 8,
      stores: ["KaBuM!", "Terabyteshop", "Pichau"],
      prices: [114.90, 116.90, 129.90],
    },
    {
      id: "M002",
      name: "Mouse Gamer Logitech G203 Rgb Lightsync Preto",
      brand: "Logitech ",
      dpi: 8.000,
      color: ["black", "white"],
      bluetooth: false,
      buttons: 6,
      stores: ["KaBuM!", "Terabyteshop", "Kalunga"],
      prices: [119.90, 129.90, 161.90],
    },
  ],
  keyboards: [
    {
      id: "K001",
      name: "Teclado Logitech K120, ABNT2",
      brand: "Logitech",
      color: ["black"],
      bluetooth: true,
      stores: ["KaBuM!", "Submarino", "Americanas"],
      prices: [59.90, 63.49, 78.00],
    },
    {
      id: "K002",
      name: "Teclado Mecanico Pichau P531 RGB",
      brand: "Pichau Gaming",
      color: ["black"],
      bluetooth: false,
      stores: ["KaBuM!", "Submarino", "Pichau"],
      prices: [229.90, 245.60, 259.99],
    },
    {
      id: "K003",
      name: "Teclado Mecanico Pichau P531 RGB",
      brand: "Pichau Gaming",
      color: ["black"],
      bluetooth: false,
      stores: ["KaBuM!", "Submarino", "Pichau"],
      prices: [229.90, 245.60, 259.99],
    },
    {
      id: "K004",
      name: "Teclado Mecanico Gamer Corsair K60 PRO",
      brand: "Corsair",
      color: ["black", "red"],
      bluetooth: true,
      stores: ["KaBuM!", "Americanas", "Pichau"],
      prices: [289.90, 325.00, 310.99],
    },
    {
      id: "K005",
      name: "Teclado Mecanico Gamer Redragon Daska, Rainbow",
      brand: "Redragon",
      color: ["black", "white"],
      bluetooth: true,
      stores: ["KaBuM!", "Magazine Luiza", "Pichau"],
      prices: [219.00, 230.60, 250.99],
    },
    {
      id: "K006",
      name: "Teclado Opto-Mecanico Redragon Infernal Dragon Viserion",
      brand: "Redragon",
      color: ["black", "red"],
      bluetooth: false,
      stores: ["Submarino", "Americanas", "Pichau"],
      prices: [419.90, 425.59, 440.00],
    },
    {
      id: "K007",
      name: "Teclado Mecanico T-Dagger Bermudo",
      brand: "T-Dagger",
      color: ["black", "grey"],
      bluetooth: true,
      stores: ["Submarino", "Americanas", "Pichau"],
      prices: [205.00, 220.99, 225.99],
    },
    {
      id: "K008",
      name: "Teclado Mecanico Gamer Corsair K60 PRO",
      brand: "Corsair",
      color: ["black", "red"],
      bluetooth: true,
      stores: ["KaBuM!", "Americanas", "Pichau"],
      prices: [289.90, 325.00, 310.99],
    },
    {
      id: "K009",
      name: "Teclado Gamer Trust GXT 835 Azor",
      brand: "Trust",
      color: ["black"],
      bluetooth: false,
      stores: ["KaBuM!", "Americanas", "Pichau"],
      prices: [149.90, 160.66, 180.99],
    },
    {
      id: "K010",
      name: "Teclado Gamer Multilaser Multimidia USB PRETO/VERDE",
      brand: "Multilaser",
      color: ["black", "green"],
      bluetooth: false,
      stores: ["KaBuM!", "Submarino", "Pichau"],
      prices: [34.90, 40.00, 43.99],
    },
  ],
  headset: [
    {
      id: "H001",
      name: "",
      brand: "",
      color: [""],
      bluetooth: true,
      stores: ["", "", ""],
      prices: [, , ],
    },
  ],
};

module.exports = produtos;
