const produtos = {
  mouses: [
    {
      id: "M001",
      name: "Mouse Gamer Cobra Chroma M711 Rgb Redragon",
      brand: "Redragon",
      dpi: 10.000,
      color: ["black", "white"],
      bluetooth: false,
      buttons: 8,
      stores: ["KaBuM!", "Terabyteshop", "Pichau"],
      prices: [114.90, 116.90, 129.90],
    },
    {
      id: "M002",
      name: "Mouse Gamer Logitech G203 Rgb Lightsync Preto",
      brand: "Logitech ",
      dpi: 8.000,
      color: ["black", "white"],
      bluetooth: false,
      buttons: 6,
      stores: ["KaBuM!", "Terabyteshop", "Kalunga"],
      prices: [119.90, 129.90, 161.90],
    },
  ],
  keyboards: [
    {
      id: "K001",
      name: "Teclado Logitech K120, ABNT2",
      brand: "Logitech",
      color: ["black"],
      bluetooth: true,
      stores: ["KaBuM!", "Submarino", "Americanas"],
      prices: [59.90, 63.49, 78.00],
    },
    {
      id: "K002",
      name: "Teclado Mecanico Pichau P531 RGB",
      brand: "Pichau Gaming",
      color: ["black"],
      bluetooth: false,
      stores: ["KaBuM!", "Submarino", "Pichau"],
      prices: [229.90, 245.60, 259.99],
    },
    {
      id: "K003",
      name: "Teclado Mecanico Pichau P531 RGB",
      brand: "Pichau Gaming",
      color: ["black"],
      bluetooth: false,
      stores: ["KaBuM!", "Submarino", "Pichau"],
      prices: [229.90, 245.60, 259.99],
    },
    {
      id: "K004",
      name: "Teclado Mecanico Gamer Corsair K60 PRO",
      brand: "Corsair",
      color: ["black", "red"],
      bluetooth: true,
      stores: ["KaBuM!", "Americanas", "Pichau"],
      prices: [289.90, 325.00, 310.99],
    },
    {
      id: "K005",
      name: "Teclado Mecanico Gamer Redragon Daska, Rainbow",
      brand: "Redragon",
      color: ["black", "white"],
      bluetooth: true,
      stores: ["KaBuM!", "Magazine Luiza", "Pichau"],
      prices: [219.00, 230.60, 250.99],
    },
    {
      id: "K006",
      name: "Teclado Opto-Mecanico Redragon Infernal Dragon Viserion",
      brand: "Redragon",
      color: ["black", "red"],
      bluetooth: false,
      stores: ["Submarino", "Americanas", "Pichau"],
      prices: [419.90, 425.59, 440.00],
    },
    {
      id: "K007",
      name: "Teclado Mecanico T-Dagger Bermudo",
      brand: "T-Dagger",
      color: ["black", "grey"],
      bluetooth: true,
      stores: ["Submarino", "Americanas", "Pichau"],
      prices: [205.00, 220.99, 225.99],
    },
    {
      id: "K008",
      name: "Teclado Mecanico Gamer Corsair K60 PRO",
      brand: "Corsair",
      color: ["black", "red"],
      bluetooth: true,
      stores: ["KaBuM!", "Americanas", "Pichau"],
      prices: [289.90, 325.00, 310.99],
    },
    {
      id: "K009",
      name: "Teclado Gamer Trust GXT 835 Azor",
      brand: "Trust",
      color: ["black"],
      bluetooth: false,
      stores: ["KaBuM!", "Americanas", "Pichau"],
      prices: [149.90, 160.66, 180.99],
    },
    {
      id: "K010",
      name: "Teclado Gamer Multilaser Multimidia USB PRETO/VERDE",
      brand: "Multilaser",
      color: ["black", "green"],
      bluetooth: false,
      stores: ["KaBuM!", "Submarino", "Pichau"],
      prices: [34.90, 40.00, 43.99],
    },
  ],
  headset: [
    {
      id: "H001",
      name: "",
      brand: "",
      color: [""],
      bluetooth: true,
      stores: ["", "", ""],
      prices: [, , ],
    },
  ],
  graphicsCard: [
    {
      id: "G001",
      name: "Placa De Video MSI GEFORCE RTX 3080 VENTUS 3X OC Edition",
      brand: "MSI",
      gpu: "NVIDIA® GeForce RTX™ 3080",
      memory: "10GB",
      stores: ["KaBuM!", "Americanas", "Pichau"],
      prices: [9299.88, 9469.00, 9600.99],
    },
    {
      id: "G002",
      name: "Placa De Video ASUS RADEON RX 6700 XT DUAL OC Edition",
      brand: "Asus",
      gpu: "AMD Radeon RX 6700 XT",
      memory: "12GB",
      stores: ["Submarino", "Americanas", "Pichau"],
      prices: [6999.91, 7103.00, 7245.99],
    },
    {
      id: "G003",
      name: "Placa De Video MANCER RADEON RX 560",
      brand: "Mancer",
      gpu: "AMD Radeon®️ RX560",
      memory: "4GB",
      stores: ["KaBuM!", "Submarino", "Pichau"],
      prices: [1179.91, 1200.00, 1350.88],
    },
    {
      id: "G004",
      name: "Placa De Video GIGABYTE GEFORCE RTX 2060 D6",
      brand: "Gigabyte",
      gpu: "GeForce RTX™ 2060",
      memory: "6GB",
      stores: ["Americanas", "Submarino", "Pichau"],
      prices: [3399.91, 3420.00, 3560.97],
    },
    {
      id: "G005",
      name: "Placa De Video ASUS GEFORCE RTX 3080 ROG STRIX WHITE Edition OC",
      brand: "Asus",
      gpu: "NVIDIA® GeForce RTX™ 3080",
      memory: "10GB",
      stores: ["KaBuM!", "Americanas", "Pichau"],
      prices: [12999.91, 13120.56, 13050.43],
    },
    {
      id: "G006",
      name: "Placa De Video AFOX RADEON R5 230",
      brand: "Afox",
      gpu: "R5 230",
      memory: "2GB",
      stores: ["Submarino", "Americanas", "Pichau"],
      prices: [299.91, 287.56, 320.99],
    },
    {
      id: "G007",
      name: "Placa De Video ZOTAC GEFORCE GTX 1660 SUPER",
      brand: "Zotac",
      gpu: "GeForce® GTX 1660 SUPER",
      memory: "6GB",
      stores: ["Submarino", "Americanas", "Pichau"],
      prices: [3399.91, 3420.56, 3560.99],
    },
    {
      id: "G008",
      name: "Placa De Video ASROCK RADEON RX 6700 XT CHALLENGER",
      brand: "ASRock",
      gpu: "AMD Radeon™ RX 6700 XT",
      memory: "12GB",
      stores: ["Submarino", "Americanas", "Pichau"],
      prices: [12999.91, 13120.56, 13050.43],
    },
    {
      id: "G009",
      name: "Placa De Video ASROCK RADEON RX 6800",
      brand: "ASRock",
      gpu: "AMD Radeon ™ RX 6800",
      memory: "16GB",
      stores: ["KaBuM!", "Americanas", "Pichau"],
      prices: [6740.92, 6800.39, 6954.43],
    },
    {
      id: "G010",
      name: "Placa De Video PNY GEFORCE GTX 970",
      brand: "PNY",
      gpu: "GeForce GTX 970",
      memory: "4GB",
      stores: ["KaBuM!", "Submarino", "Pichau"],
      prices: [1549.05, 1560.78, 1760.43],
    },
  ]
};

module.exports = produtos;
